# ==============================================================================
# Noctalia Services Configuration: Notifications, Audio, Hardware, System Monitors & Hooks
# ==============================================================================

[audio]
enable_overdrive = false
enable_sounds = false
notification_sound = ""
sound_volume = 0.5
volume_change_sound = ""


[battery]
warning_threshold = 10


[brightness]
enable_ddcutil = true
ignore_mmids = []
minimum_brightness = 0.29999998211860657
sync_all_monitors = true


[calendar]
enabled = true
refresh_minutes = 15


[hooks]
battery_charging = []
battery_discharging = []
battery_percentage_changed = []
battery_plugged = []
bluetooth_disabled = []
bluetooth_enabled = []
colors_changed = []
logging_out = [ "~/.hyprconf/hypr/scripts/notification.sh logout" ]
power_profile_changed = []
rebooting = [ "~/.hyprconf/hypr/scripts/notification.sh logout" ]
session_locked = []
session_unlocked = []
shutting_down = [ "~/.hyprconf/hypr/scripts/notification.sh logout" ]
started = [ "~/.hyprconf/hypr/scripts/notification.sh sys" ]
theme_mode_changed = []
wallpaper_changed = [ "~/.hyprconf/hypr/scripts/Wallpaper.sh set" ]
wifi_disabled = []
wifi_enabled = []


[hot_corners]
delay_ms = 0
enabled = true

    [hot_corners.bottom_left]
    action = "none"
    command = ""

    [hot_corners.bottom_right]
    action = "none"
    command = ""

    [hot_corners.top_left]
    action = "none"
    command = ""

    [hot_corners.top_right]
    action = "none"
    command = ""


[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 2.0

    [idle.behavior.lock]
    action = "lock"
    command = ""
    enabled = false
    locked_timeout = 0.0
    resume_command = ""
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    command = ""
    enabled = false
    locked_timeout = 0.0
    resume_command = ""
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    command = ""
    enabled = false
    locked_timeout = 0.0
    resume_command = ""
    timeout = 660.0


[location]
address = ""
auto_locate = false
custom_schedule = false
sunrise = ""
sunset = ""


[nightlight]
enabled = true
force = true
temperature_day = 6500
temperature_night = 5000


[notification]
background_opacity = 0.97000002861022949
border = true
collapse_on_dismiss = true
enable_daemon = true
history_retention_hours = 1
layer = "top"
max_visible = 0
monitors = []
offset_x = 10
offset_y = 8
position = "bottom_right"
scale = 1.0
show_actions = true
show_app_name = true


[osd]
background_opacity = 0.97000002861022949
border = true
enabled = true
monitors = []
offset_x = 20
offset_y = 8
orientation = "horizontal"
position = "top_center"
position_vertical = "top_center"
scale = 1.0

    [osd.kinds]
    bluetooth = true
    brightness = true
    caffeine = true
    dnd = true
    keyboard_backlight = true
    keyboard_layout = true
    lock_keys = true
    media = false
    nightlight = true
    power_profile = true
    privacy = true
    volume = true
    volume_input = true
    volume_output = true
    wifi = true


[plugins]
auto_update = "all"
enabled = [ "apex077/eyecare", "noctalia/mpvpaper", "yuuto/arch-updater" ]

    [[plugins.source]]
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    enabled = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"


[plugin_settings."noctalia/mpvpaper"]
video_directory = "~/.hyprconf/hypr/Wallpaper"


[system.monitor]
cpu_freq_activity_threshold = 2.5
cpu_freq_critical_threshold = 4.5
cpu_poll_seconds = 2.0
cpu_temp_activity_threshold = 60.0
cpu_temp_critical_threshold = 85.0
cpu_temp_sensor_path = ""
cpu_usage_activity_threshold = 50.0
cpu_usage_critical_threshold = 90.0
disk_free_activity_threshold = 80.0
disk_free_critical_threshold = 95.0
disk_free_pct_activity_threshold = 80.0
disk_free_pct_critical_threshold = 95.0
disk_poll_seconds = 10.0
disk_used_activity_threshold = 80.0
disk_used_critical_threshold = 95.0
disk_used_pct_activity_threshold = 80.0
disk_used_pct_critical_threshold = 95.0
enabled = true
gpu_poll_seconds = 5.0
gpu_temp_activity_threshold = 60.0
gpu_temp_critical_threshold = 85.0
gpu_usage_activity_threshold = 50.0
gpu_usage_critical_threshold = 95.0
gpu_vram_activity_threshold = 50.0
gpu_vram_critical_threshold = 90.0
memory_poll_seconds = 2.0
net_rx_activity_threshold = 1.0
net_rx_critical_threshold = 50.0
net_tx_activity_threshold = 1.0
net_tx_critical_threshold = 50.0
network_poll_seconds = 3.0
ram_pct_activity_threshold = 60.0
ram_pct_critical_threshold = 90.0
swap_pct_activity_threshold = 20.0
swap_pct_critical_threshold = 80.0


[weather]
effects = true
enabled = true
refresh_minutes = 30
unit = "celsius"

