# ==============================================================================
# Noctalia Lockscreen Configuration: Lockscreen Security & Lockscreen Widgets
# ==============================================================================

[lockscreen]
allow_empty_password = false
blur_intensity = 0.5
blurred_desktop = false
enabled = true
fingerprint = true
lock_before_suspend = true
monitors = []
tint_intensity = 0.30000001192092896
wallpaper = "~/.hyprconf/hypr/.cache/current_wallpaper.png"


[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 512.0
    cx = 960.0
    cy = 1007.0
    enabled = true
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface"
        background_opacity = 0.55000000000000004
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 14.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 240.0
    box_width = 528.0
    cx = 960.0
    cy = 156.0
    enabled = true
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        color = "primary"
        format = "{:%I:%M}"

