-- pywal-wal.lua
-- Applies pywal wallpaper-derived foreground colors as highlight overrides.
-- The color file (~/.cache/wal/colors-nvim.lua) is auto-generated by pywal.sh.
-- This runs AFTER catppuccin (priority 1000) so overrides land on top.

local colors_file = vim.fn.expand("~/.cache/wal/colors-nvim.lua")

local function apply_pywal_highlights()
    local ok, c = pcall(dofile, colors_file)
    if not ok or type(c) ~= "table" then
        return -- silently skip if file not yet generated
    end

    local hi = vim.api.nvim_set_hl

    -- ── Core text ────────────────────────────────────────────────────────────
    hi(0, "Normal",        { fg = c.fg,  bg = "NONE" })
    hi(0, "NormalNC",      { fg = c.fg,  bg = "NONE" })
    hi(0, "NormalFloat",   { fg = c.fg,  bg = c.c0   })
    hi(0, "FloatBorder",   { fg = c.c4,  bg = "NONE" })

    -- ── Syntax ───────────────────────────────────────────────────────────────
    hi(0, "Comment",       { fg = c.c8,  italic = true })
    hi(0, "String",        { fg = c.c6  })
    hi(0, "Character",     { fg = c.c6  })
    hi(0, "Number",        { fg = c.c4,  italic = true })
    hi(0, "Float",         { fg = c.c4,  italic = true })
    hi(0, "Boolean",       { fg = c.c3  })
    hi(0, "Identifier",    { fg = c.fg  })
    hi(0, "Function",      { fg = c.c2  })
    hi(0, "Statement",     { fg = c.c1  })
    hi(0, "Keyword",       { fg = c.c5,  bold = true })
    hi(0, "Conditional",   { fg = c.c5,  italic = true })
    hi(0, "Repeat",        { fg = c.c5,  italic = true })
    hi(0, "Operator",      { fg = c.fg  })
    hi(0, "Type",          { fg = c.c3  })
    hi(0, "StorageClass",  { fg = c.c3  })
    hi(0, "Structure",     { fg = c.c3  })
    hi(0, "PreProc",       { fg = c.c4  })
    hi(0, "Include",       { fg = c.c4  })
    hi(0, "Define",        { fg = c.c4  })
    hi(0, "Macro",         { fg = c.c4  })
    hi(0, "Special",       { fg = c.c6  })
    hi(0, "SpecialChar",   { fg = c.c6  })
    hi(0, "Error",         { fg = c.c1  })
    hi(0, "Todo",          { fg = c.bg, bg = c.c6,  bold = true })
    hi(0, "Underlined",    { fg = c.c4,  underline = true })

    -- ── Treesitter ───────────────────────────────────────────────────────────
    hi(0, "@variable",             { fg = c.fg  })
    hi(0, "@variable.builtin",     { fg = c.c3  })
    hi(0, "@variable.member",      { fg = c.fg  })
    hi(0, "@variable.parameter",   { fg = c.fg  })
    hi(0, "@constant",             { fg = c.c4  })
    hi(0, "@constant.builtin",     { fg = c.c4  })
    hi(0, "@constant.macro",       { fg = c.c4  })
    hi(0, "@module",               { fg = c.c3  })
    hi(0, "@label",                { fg = c.c5  })
    hi(0, "@string",               { fg = c.c6  })
    hi(0, "@string.escape",        { fg = c.c4  })
    hi(0, "@string.special",       { fg = c.c6  })
    hi(0, "@character",            { fg = c.c6  })
    hi(0, "@number",               { fg = c.c4  })
    hi(0, "@boolean",              { fg = c.c3  })
    hi(0, "@float",                { fg = c.c4  })
    hi(0, "@function",             { fg = c.c2  })
    hi(0, "@function.builtin",     { fg = c.c2  })
    hi(0, "@function.macro",       { fg = c.c2  })
    hi(0, "@function.method",      { fg = c.c2  })
    hi(0, "@constructor",          { fg = c.c3  })
    hi(0, "@keyword",              { fg = c.c5,  bold = true })
    hi(0, "@keyword.function",     { fg = c.c5,  bold = true })
    hi(0, "@keyword.operator",     { fg = c.c5  })
    hi(0, "@keyword.return",       { fg = c.c1,  italic = true })
    hi(0, "@keyword.import",       { fg = c.c4  })
    hi(0, "@type",                 { fg = c.c3  })
    hi(0, "@type.builtin",         { fg = c.c3  })
    hi(0, "@attribute",            { fg = c.c4  })
    hi(0, "@property",             { fg = c.fg  })
    hi(0, "@operator",             { fg = c.fg  })
    hi(0, "@punctuation.bracket",  { fg = c.c7  })
    hi(0, "@punctuation.delimiter",{ fg = c.c8  })
    hi(0, "@punctuation.special",  { fg = c.c5  })
    hi(0, "@comment",              { fg = c.c8,  italic = true })
    hi(0, "@tag",                  { fg = c.c1  })
    hi(0, "@tag.attribute",        { fg = c.c4  })
    hi(0, "@tag.delimiter",        { fg = c.c8  })

    -- ── LSP Semantic ─────────────────────────────────────────────────────────
    hi(0, "@lsp.type.function",    { fg = c.c2  })
    hi(0, "@lsp.type.keyword",     { fg = c.c5  })
    hi(0, "@lsp.type.type",        { fg = c.c3  })
    hi(0, "@lsp.type.variable",    { fg = c.fg  })
    hi(0, "@lsp.type.parameter",   { fg = c.fg  })
    hi(0, "@lsp.type.property",    { fg = c.fg  })
    hi(0, "@lsp.type.namespace",   { fg = c.c3  })
    hi(0, "@lsp.type.enum",        { fg = c.c3  })
    hi(0, "@lsp.type.enumMember",  { fg = c.c4  })
    hi(0, "@lsp.type.struct",      { fg = c.c3  })
    hi(0, "@lsp.type.interface",   { fg = c.c3  })
    hi(0, "@lsp.type.decorator",   { fg = c.c6  })
    hi(0, "@lsp.type.macro",       { fg = c.c4  })

    -- ── UI chrome ────────────────────────────────────────────────────────────
    hi(0, "LineNr",        { fg = c.c8  })
    hi(0, "CursorLineNr",  { fg = c.c4,  bold = true })
    hi(0, "CursorLine",    { fg = c.bg,  bg = c.fg  })
    hi(0, "SignColumn",    { fg = c.c8,  bg = "NONE" })
    hi(0, "StatusLine",    { fg = c.fg,  bg = c.c0 })
    hi(0, "StatusLineNC",  { fg = c.c8,  bg = c.c0 })
    hi(0, "Pmenu",         { fg = c.fg,  bg = c.c0 })
    hi(0, "PmenuSel",      { fg = c.bg,  bg = c.c4 })
    hi(0, "PmenuSbar",     { bg = c.c0  })
    hi(0, "PmenuThumb",    { bg = c.c4  })
    hi(0, "Visual",        { fg = c.bg,  bg = c.fg  })
    hi(0, "Search",        { fg = c.bg,  bg = c.c6  })
    hi(0, "IncSearch",     { fg = c.bg,  bg = c.c4  })
    hi(0, "MatchParen",    { fg = c.c6,  bold = true })
    hi(0, "WinSeparator",  { fg = c.c4  })
    hi(0, "EndOfBuffer",   { fg = c.c0  })
    hi(0, "Folded",        { fg = c.c8,  bg = c.c0  })
    hi(0, "FoldColumn",    { fg = c.c8  })

    -- ── Diagnostics ──────────────────────────────────────────────────────────
    hi(0, "DiagnosticError",       { fg = c.c1  })
    hi(0, "DiagnosticWarn",        { fg = c.c3  })
    hi(0, "DiagnosticInfo",        { fg = c.c4  })
    hi(0, "DiagnosticHint",        { fg = c.c5  })
    hi(0, "DiagnosticUnderlineError",  { sp = c.c1, underline = true })
    hi(0, "DiagnosticUnderlineWarn",   { sp = c.c3, underline = true })

    -- ── Git ──────────────────────────────────────────────────────────────────
    hi(0, "GitSignsAdd",     { fg = c.c2  })
    hi(0, "GitSignsChange",  { fg = c.c4  })
    hi(0, "GitSignsDelete",  { fg = c.c1  })

    -- ── NvimTree ─────────────────────────────────────────────────────────────
    hi(0, "NvimTreeNormal",        { fg = c.fg,  bg = "NONE" })
    hi(0, "NvimTreeFolderIcon",    { fg = c.c4  })
    hi(0, "NvimTreeFolderName",    { fg = c.c5  })
    hi(0, "NvimTreeOpenedFolderName", { fg = c.fg, bold = true })
    hi(0, "NvimTreeRootFolder",    { fg = c.c1,  bold = true })
    hi(0, "NvimTreeGitDirty",      { fg = c.c3  })
    hi(0, "NvimTreeGitNew",        { fg = c.c2  })
    hi(0, "NvimTreeGitDeleted",    { fg = c.c1  })
    hi(0, "NvimTreeIndentMarker",  { fg = c.c8  })
    hi(0, "NvimTreeWinSeparator",  { fg = c.c4  })

    -- ── Telescope ────────────────────────────────────────────────────────────
    hi(0, "TelescopeNormal",         { fg = c.fg,  bg = "NONE" })
    hi(0, "TelescopeBorder",         { fg = c.c4,  bg = "NONE" })
    hi(0, "TelescopePromptBorder",   { fg = c.c4  })
    hi(0, "TelescopeResultsBorder",  { fg = c.c4  })
    hi(0, "TelescopePreviewBorder",  { fg = c.c4  })
    hi(0, "TelescopeSelection",      { fg = c.fg,  bg = c.c0 })
    hi(0, "TelescopeSelectionCaret", { fg = c.c4  })
    hi(0, "TelescopeMatching",       { fg = c.c6,  bold = true })

    -- ── Indent Blankline ─────────────────────────────────────────────────────
    hi(0, "IblIndent",       { fg = c.c0  })
    hi(0, "IblScope",        { fg = c.c8  })

    -- ── Which-key ────────────────────────────────────────────────────────────
    hi(0, "WhichKey",        { fg = c.c4  })
    hi(0, "WhichKeyDesc",    { fg = c.fg  })
    hi(0, "WhichKeyGroup",   { fg = c.c2  })
    hi(0, "WhichKeyBorder",  { fg = c.c4  })
end

-- ── Autocmds ─────────────────────────────────────────────────────────────────
-- Apply after every colorscheme change so pywal always wins.
vim.api.nvim_create_autocmd("ColorScheme", {
    pattern = "*",
    callback = apply_pywal_highlights,
})

-- Apply on a user-defined event (triggered by pywal.sh via --remote-send).
vim.api.nvim_create_autocmd("User", {
    pattern = "PywalReload",
    callback = apply_pywal_highlights,
})

-- Return an empty lazy spec so lazy.nvim imports and executes this file.
-- All work is done by the autocmds above (ColorScheme + User PywalReload).
return {}
