# ==============================================================================
# Noctalia Bar Configuration: Left Vertical Bar Layout
# ==============================================================================

[bar]
order = [ "default" ]

    [bar.default]
    auto_hide = false
    background_opacity = 1.0
    border = "outline"
    border_width = 0.0
    capsule = false
    capsule_fill = "surface_variant"
    capsule_group = []
    capsule_opacity = 0.92000001668930054
    capsule_padding = 6.0
    capsule_radius = 15.0
    capsule_thickness = 0.80000001192092896
    center = [ "workspaces" ]
    color = "primary"
    concave_edge_corners = true
    contact_shadow = false
    enabled = true
    end = [ "tray", "network", "caffeine", "nightlight", "clipboard", "volume", "session" ]
    font_scale = 1.0
    font_weight = 500
    hover_highlight = true
    icon_color = "primary"
    layer = "top"
    margin_edge = 0
    margin_ends = 0
    margin_opposite_edge = 0
    padding = 20
    panel_overlap = 1
    position = "left"
    radius = 10
    radius_bottom_left = 10
    radius_bottom_right = 10
    radius_top_left = 10
    radius_top_right = 10
    reserve_space = true
    scale = 1.0499999523162842
    shadow = false
    show_on_workspace_switch = true
    smart_auto_hide = false
    start = [ "launcher", "date", "clock", "weather", "notifications" ]
    thickness = 35
    widget_spacing = 25

        [bar.default.dead_zone]
