# ==============================================================================
# Noctalia Bar Configuration: Full Top Bar Layout
# ==============================================================================

[bar]
order = [ "default" ]

    [bar.default]
    auto_hide = false
    background_opacity = 0.69999998807907104
    border = "primary"
    border_width = 0.0
    capsule = true
    capsule_fill = "primary"
    capsule_foreground = "on_primary"
    capsule_opacity = 1.0
    capsule_padding = 12.0
    capsule_radius = 12.0
    capsule_thickness = 0.64999997615814209
    center = [ "power_profile", "clock", "notifications", "privacy" ]
    concave_edge_corners = true
    contact_shadow = false
    enabled = true
    end = [ "widget_5", "group:g2", "group:g4", "group:g3", "group:g1", "session" ]
    font_scale = 1.0
    font_weight = 500
    hover_highlight = true
    layer = "overlay"
    margin_edge = 0
    margin_ends = 0
    margin_opposite_edge = 0
    padding = 15
    panel_overlap = 1
    position = "top"
    radius = 20
    radius_bottom_left = 20
    radius_bottom_right = 20
    radius_top_left = 20
    radius_top_right = 20
    reserve_space = true
    scale = 1.0
    shadow = false
    show_on_workspace_switch = true
    smart_auto_hide = false
    start = [ "launcher", "tray", "workspaces", "weather", "audio_visualizer" ]
    thickness = 35
    widget_spacing = 15

        [bar.default.dead_zone]

        [[bar.default.capsule_group]]
        accordion = true
        accordion_direction = "start"
        border = "primary"
        enabled = true
        fill = "primary"
        foreground = "on_primary"
        id = "g1"
        members = [ "output_volume", "input_volume" ]
        opacity = 1.0
        padding = 10.0
        radius = 16.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "on_primary"
        enabled = true
        fill = "primary"
        foreground = "on_primary"
        id = "g2"
        members = [ "caffeine", "nightlight", "clipboard" ]
        opacity = 1.0
        padding = 10.0
        radius = 16.0
        widget_spacing = 16

        [[bar.default.capsule_group]]
        accordion = true
        accordion_direction = "start"
        border = "primary"
        enabled = true
        fill = "primary"
        foreground = "on_primary"
        id = "g3"
        members = [ "ram", "cpu" ]
        opacity = 1.0
        padding = 12.0
        radius = 16.0

        [[bar.default.capsule_group]]
        accordion = true
        accordion_direction = "start"
        border = "primary"
        enabled = true
        fill = "primary"
        foreground = "on_primary"
        id = "g4"
        members = [ "wallpaper", "mpvpaper_5" ]
        opacity = 1.0
        padding = 12.0
        radius = 12.0
