[bar.default]
auto_hide = false
background_opacity = 0.0
border = "on_hover"
border_width = 0.0
capsule = true
capsule_fill = "surface_variant"
capsule_opacity = 0.92000000000000004
capsule_radius = 8
capsule_thickness = 0.84999999999999998
center = []
color = "primary"
enabled = true
end = [ "notifications", "network", "output_volume", "clock", "power_profile" ]
hover_highlight = true
icon_color = "primary"
layer = "top"
margin_edge = 10
margin_ends = 20
margin_opposite_edge = 10
padding = 26
position = "bottom"
radius = 18
reserve_space = true
scale = 1.0
shadow = true
show_on_workspace_switch = true
smart_auto_hide = false
start = [ "workspaces" ]
thickness = 36
widget_spacing = 10

[widget.clock]
format = "{:%H:%M}"
tooltip_format = "{:%A, %B %d, %Y}"

[widget.network]
show_label = false

[widget.workspaces]
label_source = "id"
max_label_chars = 5
scale = 1.2
show_labels = true
style = "minimal"
hide_when_empty = false