color0 #302721
color1 #ba754b
color2 #c99f83
color3 #c1b971
color4 #a1c171
color5 #d8baa6
color6 #d8d3a6
color7 #f3f2f2
color8 #716861
color9 #ba754b
color10 #c99f83
color11 #c1b971
color12 #a1c171
color13 #d8baa6
color14 #d8d3a6
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #231e1a
background            #231e1a
foreground            #f3f2f2
selection_foreground  #b6b2af
selection_background  #302721
active_border_color   #c99f83
inactive_border_color #302721
url_color             #c99f83

active_tab_foreground   #221e1b
active_tab_background   #c99f83
inactive_tab_foreground #b6b2af
inactive_tab_background #302721
cursor_trail_color      #b6b2af
