color0 #5a4139
color1 #ffb4ab
color2 #ffb59e
color3 #ffb59e
color4 #eac244
color5 #ffb59e
color6 #ffb59e
color7 #f7ddd5
color8 #a98a80
color9 #ffb4ab
color10 #ffb59e
color11 #ffb59e
color12 #eac244
color13 #ffb59e
color14 #ffb59e
color15 #f7ddd5

cursor                #f7ddd5
cursor_text_color     #1d100c
background            #1d100c
foreground            #f7ddd5
selection_foreground  #e2bfb5
selection_background  #5a4139
active_border_color   #ffb59e
inactive_border_color #5a4139
url_color             #ffb59e

active_tab_foreground   #5d1800
active_tab_background   #ffb59e
inactive_tab_foreground #e2bfb5
inactive_tab_background #5a4139
cursor_trail_color      #e2bfb5
