#!/usr/bin/env bash
# ==============================================================================
# colors.sh — Noctalia Dynamic Theme Palette
# Auto-generated by noctalia-colors.py. Do not edit manually.
# ==============================================================================

# Core theme colors
primary="#ac67e4"
secondary="#d65cd1"
accent="#ac67e4"
surface="#201628"
background="#201628"
foreground="#f2f2f3"
on_primary="#1f1825"
on_secondary="#1f1825"
on_surface="#f2f2f3"
error="#fd4663"
on_error="#1f1825"
muted="#6b6372"

# Terminal ANSI colors
color0="#2a1d35"
color1="#fd4663"
color2="#ac67e4"
color3="#d65cd1"
color4="#cc6694"
color5="#c493ec"
color6="#e996e5"
color7="#f2f2f3"
color8="#6b6372"
color9="#fd4663"
color10="#ac67e4"
color11="#d65cd1"
color12="#cc6694"
color13="#c493ec"
color14="#e996e5"
color15="#f2f2f3"

# UI elements
cursor="#f2f2f3"
active_border="#ac67e4"
inactive_border="#2a1d35"
