#!/usr/bin/env bash
# ==============================================================================
# colors.sh — Noctalia Dynamic Theme Palette
# Auto-generated by noctalia-colors.py. Do not edit manually.
# ==============================================================================

# Core theme colors
primary="#ffffff"
secondary="#c6c6c6"
accent="#ffffff"
surface="#131313"
background="#131313"
foreground="#e2e2e2"
on_primary="#1b1b1b"
on_secondary="#1b1b1b"
on_surface="#e2e2e2"
error="#ffb4ab"
on_error="#690005"
muted="#919191"

# Terminal ANSI colors
color0="#474747"
color1="#ffb4ab"
color2="#ffffff"
color3="#c6c6c6"
color4="#e2e2e2"
color5="#7d7d7d"
color6="#ababab"
color7="#e2e2e2"
color8="#919191"
color9="#ffb4ab"
color10="#ffffff"
color11="#c6c6c6"
color12="#e2e2e2"
color13="#7d7d7d"
color14="#ababab"
color15="#e2e2e2"

# UI elements
cursor="#e2e2e2"
active_border="#ffffff"
inactive_border="#474747"
