#!/usr/bin/env python3
"""
noctalia-colors.py — Sync Noctalia Theme & Propagate to Hyprland, Kitty & Dolphin
Triggers Noctalia template generation (when explicitly changing wallpaper),
syncs the Qt6 color scheme so Dolphin picks up the new palette,
and reloads Hyprland and Kitty configurations.
"""

import os
import re
import sys
import fcntl
import shutil
import subprocess
from pathlib import Path

HOME = os.getenv("HOME", str(Path.home()))
CACHE_DIR = Path(HOME) / ".hyprconf/hypr/.cache"
CURRENT_WALLPAPER = CACHE_DIR / "current_wallpaper.png"
LOCK_FILE = Path("/tmp/noctalia_colors_sync.lock")
SCRIPTS_DIR = Path(HOME) / ".hyprconf/hypr/scripts"
COLORS_SH = SCRIPTS_DIR / "colors.sh"


def generate_shell_colors():
    """Extract current Noctalia colors from templates and export them as bash variables
    in colors.sh for use across shell scripts and gum prompts."""
    colors = {
        "primary": "#ac67e4",
        "secondary": "#d65cd1",
        "accent": "#ac67e4",
        "surface": "#201628",
        "background": "#201628",
        "foreground": "#f2f2f3",
        "on_primary": "#1f1825",
        "on_secondary": "#1f1825",
        "on_surface": "#f2f2f3",
        "error": "#fd4663",
        "on_error": "#1f1825",
        "muted": "#6b6372",
    }

    # 1. Parse hypr/noctalia.lua
    lua_file = Path(HOME) / ".hyprconf/hypr/noctalia.lua"
    if lua_file.exists():
        try:
            for line in lua_file.read_text().splitlines():
                m = re.match(r"local\s+([a-zA-Z0-9_]+)\s*=\s*['\"]rgb\(([a-fA-F0-9]{6})\)['\"]", line)
                if m:
                    colors[m.group(1)] = f"#{m.group(2)}"
        except Exception as e:
            print(f"Warning: Failed reading noctalia.lua: {e}", file=sys.stderr)

    # 2. Parse kitty/themes/noctalia.conf
    kitty_file = Path(HOME) / ".hyprconf/kitty/themes/noctalia.conf"
    if kitty_file.exists():
        try:
            for line in kitty_file.read_text().splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split()
                if len(parts) >= 2 and parts[1].startswith("#"):
                    colors[parts[0]] = parts[1]
        except Exception as e:
            print(f"Warning: Failed reading kitty noctalia.conf: {e}", file=sys.stderr)

    # Ensure clean aliases
    colors["accent"] = colors.get("primary", "#ac67e4")
    colors["background"] = colors.get("surface", colors.get("background", "#201628"))
    colors["foreground"] = colors.get("on_surface", colors.get("foreground", "#f2f2f3"))
    colors["on_primary"] = colors.get("on_secondary", "#1f1825")
    colors["muted"] = colors.get("color8", colors.get("muted", "#6b6372"))

    content = [
        "#!/usr/bin/env bash",
        "# ==============================================================================",
        "# colors.sh — Noctalia Dynamic Theme Palette",
        "# Auto-generated by noctalia-colors.py. Do not edit manually.",
        "# ==============================================================================",
        "",
        "# Core theme colors",
        f'primary="{colors.get("primary", "#ac67e4")}"',
        f'secondary="{colors.get("secondary", "#d65cd1")}"',
        f'accent="{colors.get("accent", "#ac67e4")}"',
        f'surface="{colors.get("surface", "#201628")}"',
        f'background="{colors.get("background", "#201628")}"',
        f'foreground="{colors.get("foreground", "#f2f2f3")}"',
        f'on_primary="{colors.get("on_primary", "#1f1825")}"',
        f'on_secondary="{colors.get("on_secondary", "#1f1825")}"',
        f'on_surface="{colors.get("on_surface", "#f2f2f3")}"',
        f'error="{colors.get("error", "#fd4663")}"',
        f'on_error="{colors.get("on_error", "#1f1825")}"',
        f'muted="{colors.get("muted", "#6b6372")}"',
        "",
        "# Terminal ANSI colors",
    ]

    for i in range(16):
        key = f"color{i}"
        if key in colors:
            content.append(f'{key}="{colors[key]}"')

    cursor_val = colors.get("cursor", "#f2f2f3")
    active_b = colors.get("active_border_color", colors.get("primary", "#ac67e4"))
    inactive_b = colors.get("inactive_border_color", colors.get("surface", "#201628"))

    content.extend([
        "",
        "# UI elements",
        f'cursor="{cursor_val}"',
        f'active_border="{active_b}"',
        f'inactive_border="{inactive_b}"',
        "",
    ])

    try:
        SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
        COLORS_SH.write_text("\n".join(content))
        os.chmod(COLORS_SH, 0o755)
        print(f"Shell colors generated: {COLORS_SH}")
    except Exception as e:
        print(f"Warning: Failed writing colors.sh: {e}", file=sys.stderr)


def sync_qt6ct_colors():
    """Copy the noctalia qt6ct color scheme to the live config directory
    so Dolphin and other Qt6 apps always use the current palette."""
    src = Path(HOME) / ".hyprconf/qt6ct/colors/noctalia.conf"
    dst_dir = Path(HOME) / ".config/qt6ct/colors"
    dst = dst_dir / "noctalia.conf"
    try:
        dst_dir.mkdir(parents=True, exist_ok=True)
        if src.exists():
            shutil.copy2(src, dst)
            print(f"Qt6ct color scheme synced: {dst}")
    except Exception as e:
        print(f"Warning: Qt6ct color sync failed: {e}", file=sys.stderr)

    # Also fix the color_scheme_path in case it ever has the wrong username
    qt6ct_conf = Path(HOME) / ".config/qt6ct/qt6ct.conf"
    correct_path = str(dst)
    if qt6ct_conf.exists():
        try:
            text = qt6ct_conf.read_text()
            text = re.sub(
                r"^color_scheme_path=.*$",
                f"color_scheme_path={correct_path}",
                text,
                flags=re.MULTILINE,
            )
            qt6ct_conf.write_text(text)
        except Exception as e:
            print(f"Warning: qt6ct.conf path fix failed: {e}", file=sys.stderr)


def notify_kde_reload():
    """Signal running Qt/KDE apps (e.g. Dolphin) to reload their color palette via DBus."""
    try:
        subprocess.run(
            [
                "dbus-send", "--session", "--type=signal",
                "/KGlobalSettings", "org.kde.KGlobalSettings.notifyChange",
                "int32:3", "int32:0",
            ],
            capture_output=True, timeout=3,
        )
    except Exception:
        pass


def sync_noctalia_theme(wallpaper_path=None, explicit_change=False):
    # Only set wallpaper and trigger template generation if explicitly requested
    # (e.g. via command-line argument or WallpaperSelect).
    # When called as a hook (colors_changed), Noctalia has ALREADY changed colors
    # and applied templates — calling wallpaper-set or templates-apply here would
    # cause an infinite recursion loop!
    if explicit_change and wallpaper_path and os.path.exists(wallpaper_path):
        try:
            subprocess.run(
                ["noctalia", "msg", "wallpaper-set", wallpaper_path],
                capture_output=True,
                text=True,
                timeout=5,
            )
        except Exception as e:
            print(f"Warning: Noctalia wallpaper-set failed: {e}", file=sys.stderr)

        try:
            subprocess.run(
                ["noctalia", "msg", "templates-apply"],
                capture_output=True,
                text=True,
                timeout=5,
            )
        except Exception as e:
            print(f"Warning: Noctalia templates-apply failed: {e}", file=sys.stderr)

    # Generate colors.sh for shell scripts and gum
    generate_shell_colors()

    # Sync qt6ct color scheme so Dolphin picks up the new palette
    sync_qt6ct_colors()

    # Reload Hyprland configuration to update border colors
    subprocess.run(["hyprctl", "reload", "config-only"], capture_output=True)

    # Send SIGUSR1 to reload running Kitty instances
    subprocess.run("killall -SIGUSR1 kitty 2>/dev/null || true", shell=True)

    # Notify KDE/Qt apps (Dolphin, etc.) to reload their color palette via DBus
    notify_kde_reload()

    print("Noctalia colors applied and desktop reloaded.")


def main():
    # Use non-blocking flock to avoid overlapping / recursive executions
    lock_fd = os.open(str(LOCK_FILE), os.O_CREAT | os.O_RDWR)
    try:
        fcntl.flock(lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        # Another instance is already syncing colors, skip
        sys.exit(0)

    try:
        explicit_change = False
        wall = None
        if len(sys.argv) > 1 and os.path.exists(sys.argv[1]):
            wall = sys.argv[1]
            explicit_change = True

        sync_noctalia_theme(wall, explicit_change=explicit_change)
    finally:
        try:
            fcntl.flock(lock_fd, fcntl.LOCK_UN)
            os.close(lock_fd)
        except Exception:
            pass


if __name__ == "__main__":
    main()
