#!/usr/bin/env python3
"""
noctalia-colors.sh — Modern Wallpaper Palette & Terminal Color Engine
Extracts beautiful, readable 16-color ANSI palettes directly from active wallpaper
and propagates to Kitty and Hyprland.
"""

import os
import sys
import colorsys
import subprocess
from pathlib import Path
from PIL import Image

HOME = os.getenv("HOME", str(Path.home()))
CACHE_DIR = Path(HOME) / ".hyprconf/hypr/.cache"
CURRENT_WALLPAPER = CACHE_DIR / "current_wallpaper.png"

def get_wallpaper_path():
    if len(sys.argv) > 1 and os.path.exists(sys.argv[1]):
        return sys.argv[1]
    
    # Check noctalia state or IPC
    try:
        res = subprocess.run(["noctalia", "msg", "wallpaper-get"], capture_output=True, text=True, timeout=2)
        if res.returncode == 0 and res.stdout.strip() and os.path.exists(res.stdout.strip()):
            return res.stdout.strip()
    except Exception:
        pass
        
    if CURRENT_WALLPAPER.exists():
        try:
            target = CURRENT_WALLPAPER.resolve()
            if target.exists():
                return str(target)
        except Exception:
            pass
            
    # Default fallback from Wallpaper folder (prefer shell-ninja.png)
    default_dir = Path(HOME) / ".hyprconf/hypr/Wallpaper"
    shell_ninja = default_dir / "shell-ninja.png"
    if shell_ninja.exists():
        return str(shell_ninja)
    for ext in ["*.jpg", "*.png", "*.jpeg"]:
        for f in default_dir.glob(ext):
            return str(f)
    return None

def hex_color(r, g, b):
    return f"#{int(max(0, min(r, 1.0))*255):02x}{int(max(0, min(g, 1.0))*255):02x}{int(max(0, min(b, 1.0))*255):02x}"

def generate_palette(image_path):
    img = Image.open(image_path).convert('RGB')
    img_small = img.resize((160, 160), Image.Resampling.BILINEAR)
    
    # Quantize to 16 dominant colors from image
    img_quant = img_small.quantize(colors=16)
    raw_palette = img_quant.getpalette()[:48]
    
    extracted = []
    for i in range(0, len(raw_palette), 3):
        extracted.append((raw_palette[i]/255.0, raw_palette[i+1]/255.0, raw_palette[i+2]/255.0))
        
    def lum(c):
        return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
        
    extracted.sort(key=lum)
    
    # Dominant hue from most frequent/vibrant color
    dom_r, dom_g, dom_b = extracted[len(extracted)//2]
    h, l, s = colorsys.rgb_to_hls(dom_r, dom_g, dom_b)
    
    # Background: dark tinted with dominant hue (very readable, ~0.08 lightness)
    bg_r, bg_g, bg_b = colorsys.hls_to_rgb(h, 0.08, min(s, 0.25))
    
    # Foreground: crisp, readable off-white tinted with dominant hue (~0.90 lightness)
    fg_r, fg_g, fg_b = colorsys.hls_to_rgb(h, 0.90, min(max(s, 0.15), 0.35))
    
    # Primary accent for borders and highlights
    pri_r, pri_g, pri_b = colorsys.hls_to_rgb(h, 0.70, min(max(s, 0.40), 0.85))
    sec_r, sec_g, sec_b = colorsys.hls_to_rgb((h + 0.15) % 1.0, 0.62, 0.45)
    
    # ANSI 16 colors: standard terminal hues adjusted with wallpaper tones
    ansi_hues = [
        (h, 0.12, min(s, 0.25)),       # 0: Black (dark background tone)
        (0.00, 0.62, 0.70),             # 1: Red
        (0.33, 0.62, 0.65),             # 2: Green
        (0.12, 0.65, 0.75),             # 3: Yellow
        (0.60, 0.65, 0.70),             # 4: Blue
        (0.80, 0.65, 0.70),             # 5: Magenta
        (0.50, 0.65, 0.70),             # 6: Cyan
        (h, 0.82, min(s, 0.20)),       # 7: White
        (h, 0.38, min(s, 0.30)),       # 8: Bright Black (gray)
        (0.00, 0.75, 0.80),             # 9: Bright Red
        (0.33, 0.75, 0.75),             # 10: Bright Green
        (0.12, 0.78, 0.85),             # 11: Bright Yellow
        (0.60, 0.75, 0.80),             # 12: Bright Blue
        (0.80, 0.75, 0.80),             # 13: Bright Magenta
        (0.50, 0.75, 0.80),             # 14: Bright Cyan
        (h, 0.96, min(s, 0.15)),       # 15: Bright White
    ]
    
    ansi_rgb = [colorsys.hls_to_rgb(ah[0], ah[1], ah[2]) for ah in ansi_hues]
    
    return {
        "bg": (bg_r, bg_g, bg_b),
        "fg": (fg_r, fg_g, fg_b),
        "pri": (pri_r, pri_g, pri_b),
        "sec": (sec_r, sec_g, sec_b),
        "ansi": ansi_rgb
    }

def apply_colors(pal):
    bg_hex = hex_color(*pal["bg"])
    fg_hex = hex_color(*pal["fg"])
    pri_hex = hex_color(*pal["pri"])
    sec_hex = hex_color(*pal["sec"])
    
    # ── 1. Write Kitty Colors ──────────────────────────────────────────────────
    kitty_colors_text = (
        f"# Auto-generated by noctalia-colors.sh\n"
        f"foreground   {fg_hex}\n"
        f"background   {bg_hex}\n"
        f"cursor       {pri_hex}\n"
        f"cursor_text_color {bg_hex}\n"
        f"selection_foreground {bg_hex}\n"
        f"selection_background {pri_hex}\n\n"
        + "".join([f"color{i:<8} {hex_color(*c)}\n" for i, c in enumerate(pal["ansi"])])
    )
    
    for k_path in [
        Path(HOME) / ".config/kitty/colors-kitty.conf",
        Path(HOME) / ".hyprconf/kitty/colors-kitty.conf",
        Path(HOME) / ".cache/wal/colors-kitty.conf"
    ]:
        k_path.parent.mkdir(parents=True, exist_ok=True)
        if k_path.is_symlink():
            k_path.unlink()
        k_path.write_text(kitty_colors_text)
        
    # Update active/inactive border in kitty.conf
    for kc_path in [Path(HOME) / ".config/kitty/kitty.conf", Path(HOME) / ".hyprconf/kitty/kitty.conf"]:
        if kc_path.exists():
            content = kc_path.read_text()
            import re
            content = re.sub(r'active_border_color\s+#[0-9a-fA-F]+', f'active_border_color {pri_hex}', content)
            content = re.sub(r'inactive_border_color\s+#[0-9a-fA-F]+', f'inactive_border_color {sec_hex}', content)
            kc_path.write_text(content)
            
    # Send SIGUSR1 to reload running Kitty instances
    subprocess.run("killall -SIGUSR1 kitty 2>/dev/null || true", shell=True)
    
    # ── 2. Write Hyprland Colors ───────────────────────────────────────────────
    hypr_text = (
        "-- colors-hyprland.lua\n-- Auto-generated by noctalia-colors.sh\n"
        f'active   = "rgba({pri_hex[1:]}ee)"\n'
        f'inactive = "rgba({sec_hex[1:]}aa)"\n'
    )
    for h_path in [
        Path(HOME) / ".hyprconf/hypr/configs/colors-hyprland.lua",
        Path(HOME) / ".config/hypr/configs/colors-hyprland.lua",
        Path(HOME) / ".cache/wal/colors-hyprland.lua"
    ]:
        h_path.parent.mkdir(parents=True, exist_ok=True)
        if h_path.is_symlink():
            h_path.unlink()
        h_path.write_text(hypr_text)
        
    # Reload Hyprland
    subprocess.run(["hyprctl", "reload"], capture_output=True)
    print(f"Colors applied: BG={bg_hex}, FG={fg_hex}, Primary={pri_hex}, Secondary={sec_hex}")

def main():
    wall = get_wallpaper_path()
    if not wall or not os.path.exists(wall):
        print("No wallpaper found")
        return
    pal = generate_palette(wall)
    apply_colors(pal)

if __name__ == "__main__":
    main()
